/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenda;


import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;


/**
 *
 * @author Sebastian
 */
public final class Agenda extends javax.swing.JPanel {

    DefaultListModel model = new DefaultListModel();
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        contactos.setModel(model);
        actualizar.setEnabled(false);
       addJlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        buscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostratContactos = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        addNombre = new javax.swing.JTextField();
        addTelefono = new javax.swing.JTextField();
        addCorreo = new javax.swing.JTextField();
        addDireccion = new javax.swing.JTextField();
        addAlias = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new java.awt.BorderLayout());

        buscar.setText("Usuario Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        contactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        contactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        contactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(contactos);

        jPanel2.add(jScrollPane1);

        mostratContactos.setEditable(false);
        mostratContactos.setColumns(20);
        mostratContactos.setRows(2);
        jScrollPane2.setViewportView(mostratContactos);

        jPanel2.add(jScrollPane2);

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAdd.setText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExport.setText("Exportar");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        addNombre.setText("Nombre");
        addNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNombreMouseClicked(evt);
            }
        });

        addTelefono.setText("Telefono");
        addTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTelefonoMouseClicked(evt);
            }
        });

        addCorreo.setText("Correo");
        addCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCorreoMouseClicked(evt);
            }
        });

        addDireccion.setText("Direccion");
        addDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDireccionMouseClicked(evt);
            }
        });

        addAlias.setText("Alias");
        addAlias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAliasMouseClicked(evt);
            }
        });

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addAlias, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addDireccion)
                            .addComponent(addCorreo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnAdd))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExport)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminar)
                .addGap(32, 32, 32)
                .addComponent(addNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        Main.guardarTxt();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code 
      
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void contactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactosMouseClicked
        // TODO add your handling code here:
        Contacto resultado;
        resultado = Main.buscarIndex(contactos.getSelectedIndex());
        actualizar.setEnabled(true);
        mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
        
        addNombre.setText(resultado.getNombre());
        addTelefono.setText(Main.ListtoString(resultado.getTelefonos()));
        addDireccion.setText(resultado.getDireccion());
        addCorreo.setText(resultado.getCorreo());
        addAlias.setText(resultado.getAlias());
    }//GEN-LAST:event_contactosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String datoBuscar;
        Contacto resultado;
        datoBuscar=(String)buscar.getText();
        
        resultado = Main.buscarNombre(datoBuscar);
        
        
        if(resultado==null){
            resultado = Main.buscarTelefono(datoBuscar);
            if(resultado == null){
                resultado = Main.buscarCorreo(datoBuscar);
                if(resultado == null){
                    resultado = Main.buscarDireccion(datoBuscar);
                    if(resultado == null){
                        resultado = Main.buscarAlias(datoBuscar);
                        if(resultado == null){
                            mostratContactos.setText("Este contacto no existe");
                        }else{
                            mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                                "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                                + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
                        }
                        }else{
                            mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                                "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                                + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
                        }   
                }else{
                    mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                        "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                        + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
                }
            }else{
                mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                    "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                    + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
            }
        }else{
            mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(!addNombre.getText().equals("")){
            if(!addTelefono.getText().equals("")){
                        Contacto c;
                        ArrayList<String> numero = Main.separar(addTelefono.getText());

                        c = Main.buscarTelefono(numero);
                if(c != null){
                        mostratContactos.setText("Numero de telefono ya existe.");
                }else{
                        String nombre,correo,direccion,alias;
                        nombre = addNombre.getText();
                        correo = addCorreo.getText();
                        direccion = addDireccion.getText();
                        alias = addAlias.getText(); 
                        Main.agregarContacto(nombre, numero, correo, direccion, alias,contactos.getLastVisibleIndex()+1);
                        model.removeAllElements();
                        addJlist();
                    }   
            }else{
                    mostratContactos.setText("Por favor ingrese un numero de telefono");
                }
        }else{
                mostratContactos.setText("Porfavor ingrese un nombre");
            }   
    }//GEN-LAST:event_btnAddActionPerformed

    private void addNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNombreMouseClicked
        // TODO add your handling code here:
        String al =addNombre.getText();
        if(al.equals("Nombre")){
            addNombre.setText("");
        }
    }//GEN-LAST:event_addNombreMouseClicked

    private void addTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTelefonoMouseClicked
        // TODO add your handling code here:
        String al =addTelefono.getText();
        if(al.equals("Telefono")){
            addTelefono.setText("");
        }
    }//GEN-LAST:event_addTelefonoMouseClicked

    private void addCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCorreoMouseClicked
        // TODO add your handling code here:
        String al =addCorreo.getText();
        if(al.equals("Correo")){
            addCorreo.setText("");
        }
    }//GEN-LAST:event_addCorreoMouseClicked

    private void addDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDireccionMouseClicked
        // TODO add your handling code here:
        String al =addDireccion.getText();
        if(al.equals("Direccion")){
            addDireccion.setText("");
        }
    }//GEN-LAST:event_addDireccionMouseClicked

    private void addAliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAliasMouseClicked
        // TODO add your handling code here:
        String al =addAlias.getText();
        if(al.equals("Alias")){
            addAlias.setText("");
        }
    }//GEN-LAST:event_addAliasMouseClicked

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here:
        Contacto resultado;
        
        resultado = Main.buscarIndex(contactos.getSelectedIndex());
        resultado.setNombre(addNombre.getText());
        resultado.setAlias(addAlias.getText());
        resultado.setCorreo(addCorreo.getText());
        resultado.setDireccion(addDireccion.getText());
        resultado.setTelefonos(addTelefono.getText());

        resultado = Main.buscarIndex(contactos.getSelectedIndex());
        
        mostratContactos.setText("Nombre: "+ resultado.getNombre() + "\n" + 
                "Telefono: "+ resultado.getTelefonos()+ "\n" + "Correo: " 
                + resultado.getCorreo() + "\n" + "Direccion: "+ resultado.getDireccion()+"\n"+"Alias: "+ resultado.getAlias());
        
        model.removeAllElements();
        addJlist();
        
    }//GEN-LAST:event_actualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        Main.eliminarUsuario(contactos.getSelectedIndex());
        model.removeAllElements();
        addJlist();
    }//GEN-LAST:event_eliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField addAlias;
    private javax.swing.JTextField addCorreo;
    private javax.swing.JTextField addDireccion;
    private javax.swing.JTextField addNombre;
    private javax.swing.JTextField addTelefono;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExport;
    private javax.swing.JTextField buscar;
    private javax.swing.JList<String> contactos;
    private javax.swing.JButton eliminar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mostratContactos;
    // End of variables declaration//GEN-END:variables

 public void addJlist(){
     for(Contacto c : Main.AgendaContactos){
         model.addElement(c.getNombre());
     }
 }
}
